### ISSUE TITLE
game breaks on press of "u"

### ISSUE THREAD

**Issue by AAspCodes** [kaisunc/vscodevimacademy#15]
https://user-images.githubusercontent.com/46567012/143818517-752ea0a6-8d7e-414a-b1a5-65a8ab9e288f.mov

in the video, you can see what happens when I press "u" it happens slightly differently each time, but every time, text that wasn't supposed to be there appears.
This is an awesome project btw!

**Comment by kaisunc** [comment]
My advice is... don't use keys that's outside the scope of the
level(especially undo, redo) .
"u" is undo, so it's undoing the updated text from the game every time a
task is completed. It's one of those things i can't really account for in
the game since the undo buffer is always going to be there. It's kind of
like a "soft" boundary in the game which can't be fenced off.
